### PR TITLE
Virtual tables

### PR DESCRIPTION
**Pull request by sbooth**
Allow virtual tables modules to be more easily created using Swift

### CODE REVIEW

**Comment by wildthink** [comment]
This looks great! Thanks for putting it all together.

**Comment by sbooth** [comment]
Thanks for taking a look. The interface isn't quite what I'd like it to be because the objects have to be passed in and out of C functions as `void *` but it seems workable. I'd like to use associated typed in `VirtualTableModule` and `VirtualTableCursor` but I haven't figured out a way to preserve associated type information through a C interface since the the types aren't known until runtime.

Hopefully I will get non-eponymous virtual tables working soon.

**Comment by wildthink** [comment]
Not sure exactly how you mean but would capturing the Type in a var of the VirtualTableModuleClientData or reified VirtualTableModule work?

**Comment by sbooth** [comment]
I've tried something like this to no avail:
```
let str = "string"
let type_ptr = Unmanaged.passRetained(String.self as AnyObject).toOpaque()
let str_ptr = Unmanaged.passRetained(str as AnyObject).toOpaque()
let type2 = Unmanaged<AnyObject>.fromOpaque(type_ptr).takeRetainedValue() as! Any.Type
let str22 = Unmanaged<AnyObject>.fromOpaque(str_ptr).takeRetainedValue() as! type2
error: use of undeclared type 'type2'
```
because `type2` isn't known at compile-time which is required by Swift's static typing.

**Comment by wildthink** [comment]
You just want it cast the Protocol? Can you provide (non-working) code of what you would like to happen? Is some sort of type erasure strategy required? Maybe some variant of this https://gist.github.com/wildthink/51eafa5b43f3cc9bfe7dc5b1e392a496 ?

**Comment by wildthink** [comment]
I've been trying to replicate the series.c example. Strangely it works with the basic query
`SELECT value FROM sequential_integers LIMIT 5;`
but NOT
`SELECT value FROM sequential_integers WHERE start=1 AND stop=50 LIMIT 5;`

Code
```
extension FeistyDBTests {
    
    // trying to match
    // https://sqlite.org/src/file/ext/misc/series.c
        func testSeqVirtualTable() {
            final class SequentialIntegerModule: VirtualTableModule {
                
                final class Cursor: VirtualTableCursor {
                    let module: SequentialIntegerModule
                    var _rowid: Int64 = 0
                    var _start: Int64 = 0
                    var _stop: Int64 = 5
                    var _step: Int64 = 1
                    var _value: Int64 = 0

                    init(_ module: SequentialIntegerModule) {
                        self.module = module
                    }

                    func column(_ i: Int) throws -> DatabaseValue {
                        switch i {
                        case 2: return .integer(_start)
                        case 3: return .integer(_stop)
                        case 4: return .integer(_step)
                        default:
                            return .integer(_value)
                        }
                        
                    }

                    func next() throws {
                        _rowid += 1
                        _value += _step
                    }

                    func rowid() throws -> Int64 {
                        return _rowid
                    }

                    func filter(_ arguments: [DatabaseValue], indexNumber: Int, indexName: String?) throws {
                        _rowid = 1
                        _value = _start
                    }

                    func eof() throws -> Bool {
                        self.module
                        return _value >= _stop
                    }
                }

                required init(arguments: [String]) {
                    Swift.print(arguments)
                }

                var declaration: String {
                    """
                    CREATE TABLE x(
                      value,
                      start HIDDEN DEFAULT 1,
                      stop HIDDEN DEFAULT 100,
                      step HIDDEN DEFAULT 1
                    )
                    """
    //                "CREATE TABLE x(value INTEGER)"
                }

                func bestIndex(_ indexInfo: inout sqlite3_index_info) throws {
                }

                func openCursor() throws -> VirtualTableCursor {
                    return Cursor(self)
                }
            }

            let db = try! Database()

            try! db.addModule("sequential_integers", type: SequentialIntegerModule.self)
            let statement = try! db.prepare(sql: "SELECT value FROM sequential_integers(1, 10) LIMIT 5;")
//            let statement = try! db.prepare(sql: "SELECT value FROM sequential_integers WHERE start=1 AND stop=50 LIMIT 5;")
//            let statement = try! db.prepare(sql: "SELECT value FROM sequential_integers LIMIT 5;")

            try! statement.execute()
            try! statement.results {
                Swift.print($0)
            }
            
            let results: [Int] = statement.map(
                {
                    Swift.print ($0)
                    return try! $0.value(at: 0)
                }
            )
            XCTAssertEqual(results, [1,2,3,4,5])
        }

}
```

**Comment by sbooth** [comment]
I think for the series table to work you need to implement the magic in `filter()` and `bestIndex()` based on the passed-in constraints. I'd also like to implement that as a demo but I haven't had a chance yet.

**Comment by wildthink** [comment]
I'm starting to wrap my head around the magic. Not quite there but I update the code above to what I have so far. The query runs and spews a trace.

What I understand so far is the `hidden` columns are actually checked as part of the regular WHERE clause. The `bestIndex` passes a flag indicating which hidden columns are seen. These flags are given to the `filter` function but there isn't any way (I can see) to get the initial values for the curser with just those two functions.

Its late for me (12 EST) so will look tomorrow. Hope there is some way to access the values from the query itself.

**Comment by sbooth** [comment]
The trampoline idea is interesting but I haven't been able to figure it out yet. I previously tried type erasure with no luck.

Here is how I'd like the protocols to look:

```swift
protocol Cursor {
	associatedtype T: Table where T.C == Self
	var table: T { get }
	init(_ table: T)
}

protocol Table {
	associatedtype C: Cursor where C.T == Self
	func openCursor() -> C
}

extension Table {
	func openCursor() -> C {
		return C(self)
	}
}
```

**Comment by wildthink** [comment]
How about this?
```
protocol Cursor {
    associatedtype T: Table where T.C == Self
    var table: T { get }
    init(_ table: T)
}

protocol Table {
    associatedtype C: Cursor where C.T == Self
    var type: C.Type { get }
    func openCursor() -> C
}

extension Table {
    func openCursor() -> C {
        return type.init(self)
    }
}
```

**Comment by sbooth** [comment]
Nice article! Maybe next time it'll be FeistyDB instead of SQift!

Regarding your table/cursor implementation, do you have an example of how the type information would survive conversion to an opaque pointer and back?

**Comment by wildthink** [comment]
I wish I had found FeistyDB first! Plan of updating the example to use it!
I guess I'm fuzzy on the context of the conversion back and when/if you need to know the underlying type and not just the `protocol`.

**Comment by sbooth** [comment]
Protocols with associated types (PATs) can only be used as generic constraints. For example,

```swift
protocol Holder1 {
	var obj: AnyObject { get }
}

protocol Holder2 {
	associatedtype T
	var obj: T { get }
}

if let s = t as? Holder1 {
	// works
}

if let s = t as? Holder2 {
	// compiler error: Protocol 'Holder2' can only be used as a generic constraint because it has Self or associated type requirements
}
```

so I don't think there is a way to recover the object from a `void *` that under the hood is a `VirtualTableModule` if `VirtualTableModule` is a PAT.

**Comment by wildthink** [comment]
Ah, yes this is a problem. Is it really necessary to have the associated types? `Tables` and `Cursors` are always defined together. The `Cursor` has its `var module:` which is already strongly typed and all the glue can be content the basic protocols (so it seems).

refs:
https://www.bobthedeveloper.io/blog/generic-protocols-with-associated-type
https://medium.com/better-programming/swift-protocols-with-associated-types-and-generics-373b2927baed

**Comment by wildthink** [comment]
Also, I think the return value should be provided by the `bestIndex()`. Sometimes the logic should return other than SQLITE_OK.
```
func bestIndex(_ indexInfo: inout sqlite3_index_info) throws -> Int32 {
```

**Comment by sbooth** [comment]
I've gone back and forth about returning status codes vs. throwing errors as you can see by some of the commits in this PR.

Right now it's possible for `bestIndex()` to return a value other than `SQLITE_OK` by throwing an appropriate `SQLiteError`. The advantage of this is that it sets the return code and also allows the implementation to pass on a more descriptive message (`zErrMsg`). The disadvantage is that is may not be intuitive to throw for all non-`SQLITE_OK` cases.

**Comment by wildthink** [comment]
The other case is `SQLITE_CONSTRAINT` which is not an error but does influence the query planning.

see 2.3.3 Return Value in
https://sqlite.com/vtab.html

**Comment by sbooth** [comment]
That was actually the issue that started my back-and-forth on return codes vs. throwing errors.

Right now you can throw a `.constraint()` error:

https://github.com/feistydog/FeistyDB/blob/3ddfb1c2798e2ed0f15640444e5001230146f0a9/FeistyDBTests/FeistyDBTests.swift#L692

(Technically you can also throw an `.ok()` error but that makes no sense.)

Whether it makes more sense to throw a constraint error or return a code (which probably isn't an actual error but more of a status/result) is probably a good discussion to have.

**Comment by wildthink** [comment]
Ah. I would tend (at least in the case of the `bestIndex()` ) towards return codes, perhaps even making them an enum to avoid the "unswifty" `SQLITE_OK` et al.

**Comment by sbooth** [comment]
> Ah. I would tend (at least in the case of the `bestIndex()` ) towards return codes, perhaps even making them an enum to avoid the "unswifty" `SQLITE_OK` et al.

I think this makes sense because there are two possible return values which according to SQLite are not errors but influence the query planner.

```
** If an error occurs, pParse is populated with an error message and an
** appropriate error code is returned.  A return of SQLITE_CONSTRAINT from
** xBestIndex is not considered an error.  SQLITE_CONSTRAINT indicates that
** the current configuration of "unusable" flags in sqlite3_index_info can
** not result in a valid plan.
```

> Is the `.constraint()` error translated to the return value internally so sqlite will try other index strategies?

Yes, but this is not as relevant with the latest changes.

**Comment by wildthink** [comment]
What can I do best help?

**Comment by sbooth** [comment]
Take a hard look at the API to ensure it makes sense?

I have non-eponymous virtual tables working now but I'm not sure that the current `addModule` makes sense. Specifically, whether it makes sense to have `eponymousOnly` be a defaulted parameter, and it so, if `true` makes sense as a default.

**Comment by wildthink** [comment]
Still thinking/researching but I think eponymous tables are a very common use so the default setting is OK IMO. I'm trying to concoct a scenario where I would need to distinguish between a create and a connect and testing to see when the args are provided in the init and how things work with an explicit `CREATE VIRTUAL TABLE ...`.

**Comment by wildthink** [comment]
FWIW I find these `DatabaseValue` extensions handy.

``` swift
extension DatabaseValue: ExpressibleByNilLiteral {
    public init(nilLiteral: ()) {
        self = .null
    }
}

extension DatabaseValue: ExpressibleByIntegerLiteral {
    public init(integerLiteral value: IntegerLiteralType) {
        self = .integer(Int64(value))
    }
}

extension DatabaseValue: ExpressibleByStringLiteral {
    public init(stringLiteral value: StringLiteralType) {
        self = .text(value)
    }
}

extension DatabaseValue: ExpressibleByFloatLiteral {
    public init(floatLiteral value: FloatLiteralType) {
        self = .float(value)
    }
}

extension DatabaseValue: ExpressibleByBooleanLiteral {
    public init(booleanLiteral value: BooleanLiteralType) {
        self = .integer(value ? 1 : 0)
    }
}
```

**Comment by sbooth** [comment]
Thanks for those extensions, they are handy!

I've been thinking about ways to better handle the virtual table lifecycle, especially virtual tables intended to be persistent (like FTS5). The lifecycle of a virtual table is:

1. xCreate() -> Creates a new virtual table (`CREATE TABLE`) along with any associated backing store

Possibly repeated:

2. xConnect() -> Establishes a connection to an existing virtual table
3. xDisconnect() -> Closes a connection to an existing virtual table

Finally, possibly weeks/months in the future:

4. xDestroy() -> Destroys a virtual table (`DROP TABLE`) and the associated backing store

The current implementation doesn't allow the separation of create and destroy operations from connect and disconnect operations. That is something I'd like to remedy.

Also, although I may not implement writable virtual tables now, I'd also like to have an API that could accommodate it (more or less) without major changes. Perhaps a protocol inheriting from `VirtualTableModule`?

**Comment by wildthink** [comment]
It’s all quite cool. I’m been working on swiftifying the test case. I’ll forward it when it done so you can take a look. I also have some plans for adding some additional VTables, one being for UserDefaults to start with.

Also I’ve more additions on my fork that I’d be happy to have included if you are interested.

I’ll keep you posted.

Thanks again for this addition!!

Jason

**Comment by wildthink** [comment]
What do you think of this?

``` swift
class FDVirtualTableTests: XCTestCase {

    let db = try! Database()

    override func setUpWithError() throws {
        try! db.addModule("generate_series", type: SeriesModule.self)
    }

    override func tearDownWithError() throws {
    }

    func testSeriesVirtualTable_Limit() {

        let statement = try! db.prepare(sql: "SELECT value FROM generate_series LIMIT 5;")
        let results: [Int] = statement.map({try! $0.value(at: 0)})
        XCTAssertEqual(results, [0,1,2,3,4])
    }
    
    func testSeriesVirtualTable_Start() {
        
        let statement = try! db.prepare(sql: "SELECT value FROM generate_series(10) LIMIT 5;")
        let results = statement.map({try! $0.value(at: 0)})
        XCTAssertEqual(results, [10,11,12,13,14])
    }
    
    func testSeriesVirtualTable_AllOptions() {

        let statement = try! db.prepare(sql: "SELECT value FROM generate_series(10, 20, 1) LIMIT 5;")
        let results = statement.map({try! $0.value(at: 0)})
        XCTAssertEqual(results, [10,11,12,13,14])
    }
    
    func testSeriesVirtualTable_Step2() {

        let statement = try! db.prepare(sql: "SELECT value FROM generate_series(10, 20, 2) LIMIT 5;")
        let results = statement.map({try! $0.value(at: 0)})
        XCTAssertEqual(results, [10,12,14,16,18])
    }
}

struct QueryPlanOption: OptionSet {
    struct Info {
        var name: String
        var index: Int
    }
    static var info:[Int:Info] = [:]
    static subscript(_ ndx: Int) -> Info {
        return info[ndx] ?? Info(name: "<INFO>", index: ndx)
    }
    static subscript(_ ndx: Int32) -> Info {
        return info[Int(ndx)] ?? Info(name: "<INFO>", index: Int(ndx))
    }

    let rawValue: Int32

    init(rawValue: Int32) {
        self.rawValue = rawValue
    }

    init(index: Int32) {
        self.rawValue = (1 << index)
    }

    init(_ name: String? = nil, _ ndx: Int) {
        self.rawValue = Int32(1 << ndx)
        if let name = name {
            QueryPlanOption.info[self.index] = Info(name: name, index: self.index)
        }
    }

    var index: Int { rawValue.trailingZeroBitCount }
    var popcount: Int { rawValue.nonzeroBitCount }

    var info: Info { return Self[index] }
    
    static let value    = QueryPlanOption("value", 0)
    static let start    = QueryPlanOption("start", 1)
    static let stop     = QueryPlanOption("stop", 2)
    static let step     = QueryPlanOption("step", 3)
    static let descending = QueryPlanOption("descending", 4)
    
    static var all: QueryPlanOption = [.value, .start, .stop, .step, .descending]
}

///////////////////////////////////////////////////////
/// A port of the `generate_series` sqlite3 module
/// - seealso: https://www.sqlite.org/src/file/ext/misc/series.c
final class SeriesModule: VirtualTableModule {

    final class Cursor: VirtualTableCursor {
        let module: SeriesModule
        var _isDescending = false
        var _rowid: Int64 = 0
        var _value: Int64 = 0
        var _min: Int64 = 0
        var _max: Int64 = 0
        var _step: Int64 = 0

        init(_ module: SeriesModule) {
            self.module = module
            _ = QueryPlanOption.all // Make sure all static options are in info
        }

        func column(_ index: Int32) -> DatabaseValue {
            switch index {
            case 1: return .integer(_min)
            case 2: return .integer(_max)
            case 3: return .integer(_step)
            default:
                return .integer(_value)
            }
        }

        func next() {
            _value += (_isDescending ? -_step : _step)
            _rowid += 1
        }

        func rowid() -> Int64 {
            return _rowid
        }

        func filter(_ arguments: [DatabaseValue], indexNumber: Int32, indexName: String?) {
            let opt = QueryPlanOption(rawValue: indexNumber)
            func get_opt(p: QueryPlanOption, argc: Int, else v: Int64) -> (Int64, Int) {
                if opt.contains(p), case let .integer(i) = arguments[argc] {
                    return (i, argc + 1)
                }
                return (v, argc)
            }
            
            var argc = 0
            (_min, argc) = get_opt(p: .start, argc: argc, else: 0)
            (_max, argc) = get_opt(p: .stop, argc: argc, else: 100) // 0xffffffff
            (_step, argc) = get_opt(p: .step, argc: argc, else: 1)

            _isDescending = opt.contains(.descending)
            _value = _isDescending ? _max : _min

            if _isDescending && _step > 0 {
                _value -= (_max - _min) % _step
            }
            _rowid = 1
        }

        var eof: Bool {
            _isDescending ? (_value < _min) : (_value > _max)
        }
    }

    required init(arguments: [String]) {
        Swift.print("init", arguments)
    }

    var declaration: String {
        "CREATE TABLE x(value,start hidden,stop hidden,step hidden)"
    }

    var options: Database.VirtualTableModuleOptions {
        return [.innocuous]
    }

    func bestIndex(_ indexInfo: inout sqlite3_index_info) -> VirtualTableModuleBestIndexResult {
        // Inputs
        let constraintCount = Int(indexInfo.nConstraint)
        let constraints = UnsafeBufferPointer<sqlite3_index_constraint>(start: indexInfo.aConstraint, count: constraintCount)

        // Outputs
        let constraintUsage = UnsafeMutableBufferPointer<sqlite3_index_constraint_usage>(start: indexInfo.aConstraintUsage, count: constraintCount)

        var queryPlan = QueryPlanOption()
        _ = QueryPlanOption.all // force Info[] population
        
        for constraint in constraints {
            guard constraint.op == SQLITE_INDEX_CONSTRAINT_EQ else { return .constraint }
            let ndx = constraint.iColumn
            guard constraint.usable != 0 else { continue }
            let opt = QueryPlanOption(index: ndx)
//            Swift.print("plan union", opt.info)
            queryPlan = queryPlan.union(opt)
        }
        Swift.print(queryPlan.info)
        for (ndx, col) in queryPlan.elements().enumerated() {
//            Swift.print("usage", ndx, col.info)
            constraintUsage[col.index - 1].argvIndex = Int32(ndx + 1)
        }
        Swift.print (#line, queryPlan)
        
        if queryPlan.contains(.start) && queryPlan.contains(.stop) {
            // Lower the cost if we also have step
            indexInfo.estimatedCost = 2  - (queryPlan.contains(.step) ? 1 : 0)
            indexInfo.estimatedRows = 1000
            
            // ORDER BY
            if indexInfo.nOrderBy == 1 {
                if indexInfo.aOrderBy[0].desc == 1 {
                    queryPlan = queryPlan.union(.descending)
                }
                indexInfo.orderByConsumed = 1
            }
        }
        else {
            indexInfo.estimatedRows = 2147483647
        }
        // Passed to filter()
//        indexInfo.idxStr =
        indexInfo.idxNum = queryPlan.rawValue

        return .ok
    }
    func openCursor() -> VirtualTableCursor {
        return Cursor(self)
    }
}

public extension OptionSet where RawValue: FixedWidthInteger {

    func elements() -> AnySequence<Self> {
        var remainingBits = rawValue
        var bitMask: RawValue = 1
        return AnySequence {
            return AnyIterator {
                while remainingBits != 0 {
                    defer { bitMask = bitMask &* 2 }
                    if remainingBits & bitMask != 0 {
                        remainingBits = remainingBits & ~bitMask
                        return Self(rawValue: bitMask)
                    }
                }
                return nil
            }
        }
    }
}
}


```

**Comment by wildthink** [comment]
Any reason not to make `func rowid() -> Int64 {}` a `var rowed: Int64`?

**Comment by sbooth** [comment]
>What do you think of this?

I like the use of `OptionSet` for the query plan!

> Any reason not to make `func rowid() -> Int64 {}` a `var rowed: Int64`?

I thought about this also. `xRowid()` is allowed to return `SQLITE_ERROR`, and although I couldn't come up with a case off the top of my head where it wouldn't be possible to return a rowid, I wanted to leave the option open so declared it as `func rowid() throws -> Int64` in the protocol.

**Pull request merged**
